# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiante: Gerald D. Chaves Chacón. 

### Crear un array a partir de una lista

In [1]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

In [4]:
#Código crear un array de ceros de tamaño 5x5
array_ceros = np.zeros((5,5))
print(array_ceros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [5]:
#Código crear un array de unos de tamaño 3x3
array_unos = np.ones((3,3))
print(array_unos)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [6]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array_lineal = np.linspace(0,9,10)
print(array_lineal)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [7]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array_reto = np.linspace(0,1,6)
print(array_reto)

[0.  0.2 0.4 0.6 0.8 1. ]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [15]:
#array_salario = np.array([500,400,200])
#array_propinas = np.array([6,4,9])

#Este sería otra opción de suma de matrices
array_salario = np.array([[500,400,200],[350,290,500]])
array_propinas = np.array([[6,4,9],[2,10,50]])

#Código realizar una suma, resta, multiplicación y división entre dos arrays

# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''


suma = array_salario + array_propinas
resta = array_salario - array_propinas
multiplicacion = array_salario * array_propinas
division = array_salario / array_propinas

print("La suma del salario más propinas es de: ",suma)
print("La resta del salario más propinas es de: ",resta)
print("La multiplicacion del salario más propinas es de: ",multiplicacion)
print("La division del salario más propinas es de: ",division)

La suma del salario más propinas es de:  [[506 404 209]
 [352 300 550]]
La resta del salario más propinas es de:  [[494 396 191]
 [348 280 450]]
La multiplicacion del salario más propinas es de:  [[ 3000  1600  1800]
 [  700  2900 25000]]
La division del salario más propinas es de:  [[ 83.33333333 100.          22.22222222]
 [175.          29.          10.        ]]


In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [21]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])




# Calcular la media
media = np.mean(array_numeros)
print(f'La media es: {media}')
#media = np.mean(array_numeros)
#print(f'La media es:, {media}')

# Calcular la suma
suma = np.sum(array_numeros)
print(f'La suma es: {suma}')


# Calcular el valor mínimo
minimo = np.min(array_numeros)
print(f'El valor mínimo es: {minimo}')


# Calcular el valor máximo
maximo = np.max(array_numeros)
print(f'El valor máximo es: {maximo}')

'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


La media es: 3.0
La suma es: 15
El valor mínimo es: 1
El valor máximo es: 5


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [22]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = array_original.reshape(2,3)
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)


'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

Array original: [1 2 3 4 5 6]
Array reshapeado: [[1 2 3]
 [4 5 6]]


'\n# Imprimir el array original y el reshapeado\nprint("Array original:", array_original)\nprint("Array reshapeado:", array_reshapeado)\n'

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)



# | Ejercicios Reales o Prácticos | 

In [ ]:
# Preferencias películas [Acción, Comedia, Drama]

# Datos de gustos de peliculas de mariana segun accion, comedia, drama.
mariana = np.array([7,9,2])

# Vamos a evaluar que tanta acccion, que tanta comedia y que tanto drama tiene Avatar
avatar = np.array([10, 1, 5]) # Definida como mas accion y menos comedia.
grow_up = np.array([1, 10, 7]) # Definida como mas comedio y menos accion.


# Calcular la similitud de cada pelicula con los gustos de Mariana
similitud_p1 = np.dot(mariana,avatar)
similitud_p2 = np.dot(mariana,grow_up)

print(f'Similitud de preferencias de la pelicula Avatar: {similitud_p1}')
print(f'Similitud de preferencias de la pelicula Grow Up: {similitud_p2}')


if similitud_p1 > similitud_p2:
    print('Te recomendamos que veas Avatar.')
else:
    print('Te recomendamos que veas Grow Up.')

Similitud de preferencias de la pelicula Avatar: 89
Similitud de preferencias de la pelicula Grow Up: 111
Te recomendamos que veas Grow Up.


In [25]:

mariana = np.array([7,9,2])


avatar = np.array([10,1,5]) #Mas accion y menos comedia
brave_heart = np.array([8,1,7]) # Mas accion y menos accion


#Calcular la similitud de cada pelicula con los gusto de Mariana


similitud_p1 = np.dot(mariana,avatar)
similitud_p2 = np.dot(mariana,brave_heart)


print(f'Similitud de preferencias Avatar: {similitud_p1}')
print(f'Similitud de preferencias Brave Heart: {similitud_p2}')


if similitud_p1 > similitud_p2:
    print('Recomendamos Avatar')
else:
    print('Recomendamos Brave Heart')

Similitud de preferencias Avatar: 89
Similitud de preferencias Brave Heart: 79
Recomendamos Avatar


## CASO #2 

In [31]:
import numpy as np
#Datos Tipo Cambio Dolar Ultimos 10 meses | IPC , metrica mesual


tipo_cambio = np.array([506.96,505.00,504.27,505.52,506.23,506.23,506.23,506.58,506.87,507.25])
ipc = np.array([109.46,109.55,109.71,109.57,109.70,109.33,108.85, 109.36,110.39,110.79])


#Calcular coeficiente de correlación
correlacion = np.corrcoef(tipo_cambio,ipc)[0,1]


print(f'Coeficiente de correlación: {correlacion:.2f}')

Coeficiente de correlación: 0.32


## CASO #3 Estudio de Horas vrs Notas

In [51]:
# Datos: Hras de estudio y Notas Obtenidas
import numpy as np

horas_estudio = np.array([1,2,3,4,5,6,7,8,9,10]) # horas estudio
notas = np.array([50,55,60,63,67,72,75,78,81,85]) # notas obtenidas


# Calculo de correlacion de los array
# Calculo crecimiento del promedio del puntaje por hora de estudio
diferencia_notas = np.diff(notas) # Diferencia entre notas consecutivas

# Calcular el promedio del incremento de notas
incremento_notas = np.mean(diferencia_notas)

#Esta es la diferencia de la nota uno con la nota dos, la dos con la tres, etc...
print(diferencia_notas)

#print(incremento_notas)                                                              #para poner decimales
print(f'EL incremento del promerdio por cada hora de estudio es de: {incremento_notas:.2f}')

# Para mostrar el dato del array del campo 3 del indice, empiza en 0.
print(f'Esta es la cuarta nota de la lita: {notas[3]}')


# Estimacion del puntaje si estudio 12 horas
# 2 horas mas que la ultimo valor de horas_estudio (10)
objetivo_horas_estudiar = 12

puntos_a_obtener = (objetivo_horas_estudiar - max(horas_estudio)) * incremento_notas 
nota_a_obtener = (objetivo_horas_estudiar - max(horas_estudio)) * incremento_notas + max(notas)


print(f'Si estudias 2 horas mas, vas a tener {puntos_a_obtener:.2f} puntos mas que la ultima vez.')
print(f'Si estudias 2 horas mas, vas a sacarte un {nota_a_obtener:.2f} en la nota.')


# Estimacion del puntaje minin que obtendre si estudio 6 horas
objetivo_minimo_horas_estudiar = 6

puntos_a_obtener_min = (objetivo_horas_estudiar - min(horas_estudio)) * incremento_notas 
nota_a_obtener_min = (min(horas_estudio) - objetivo_minimo_horas_estudiar) * incremento_notas + min(notas)

print(f'Si estudias 6 horas, vas a tener {puntos_a_obtener_min:.2f} en la nota.')
print(f'Si estudias 6 horas, el minimo de la nota puede ser de {nota_a_obtener_min:.2f}')


[5 5 3 4 5 3 3 3 4]
EL incremento del promerdio por cada hora de estudio es de: 3.89
Esta es la cuarta nota de la lita: 63
Si estudias 2 horas mas, vas a tener 7.78 puntos mas que la ultima vez.
Si estudias 2 horas mas, vas a sacarte un 92.78 en la nota.
Si estudias 6 horas, vas a tener 42.78 en la nota.
Si estudias 6 horas, el minimo de la nota puede ser de 30.56


In [52]:
import numpy as np
#Datos: Horas de estudio y Notas Obtenidas


horas_estudio = np.array([1,2,3,4,5,6,7,8,9,10]) # Horas de estudio
notas = np.array([50,55,60,63,67,72,75,78,81,85]) # Notas Obtenida


#Cálculo crecimiento del promedio del puntuje por hora de estudio
diferencias_notas = np.diff(notas)# Difrencias entre notas consecutivas
incremento_notas = np.average(diferencias_notas)


#Estimación del puntaje si estudio 12 horas
proyeccion_estudio= 12
nota_estimada = (proyeccion_estudio - max(horas_estudio)) * incremento_notas + max(notas)



print(f"El incremento del promedio por cada hora de estudio {incremento_notas:.2f}")
print(nota_estimada)

El incremento del promedio por cada hora de estudio 3.89
92.77777777777777
